[package]
name = "nxfuse"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
time = "0.1.34"
libc = "0.2.1"
byteorder = "0.4.2"
fuse = "0.2.7"

[dependencies.nx]
git = "https://github.com/NoLifeDev/nx-rs.git"
